### ISSUE TITLE
Tracking and Chemical Implants are uselessly useful.

### ISSUE THREAD

**Issue by ScalesyScales** [Occulus-Server/Occulus-Eris#324]
#### Description of issue
Aegis has the tracking and chemical implant boxes available to use if they so choose, but they only work _within_ security, completely nullifying the whole point of using either of them. As well, the scanner device that comes with the tracking kit does not pick up tracking implants.

#### Difference between expected and actual behavior
You expect to be able to implant someone with either implant, then be able to let them leave so you don't actually need to use the brig. If they do something stupid, you can just use them to locate them with the tracker. Currently, unless the person you want to keep track of is in a cell in front of you, there's nothing you can do.

#### Steps to reproduce 
Take either kit, implant self. Leave.

#### Specific information for locating

tracking implant kit
chemical implant kit

#### Length of time in which bug has been known to occur

Not sure, maybe a long time?

#### Client version, Server revision & Game ID

master - 2021-03-07

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
fixed in #456
